language: node_js
sudo: required
dist: trusty
node_js:
  - 12
script:
  - npm install
  - npm run build
deploy:
  provider: pages:git
  token: $GH_TOKEN
  edge: true
  repo: $TRAVIS_REPO_SLUG
  local_dir: dist
